---
- name: create directories and transfer files
  block:
    - name: create directory
      ansible.builtin.file:
        path: "{{ path }}"
        state: directory
        mode: "0755"
        recurse: true

    - name: transfer template files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ path }}/{{ item.dest }}"
        mode: "{{ item.mode }}"
      loop:
        - { src: 'env.j2', dest: '.env', mode: '0644' }
        - { src: 'alertmanager.yml.j2', dest: 'alertmanager.yml', mode: '0644' }
        - { src: 'alert_rules.yml.j2', dest: 'alert_rules.yml', mode: '0644' }
        - { src: 'prometheus.yml.j2', dest: 'prometheus.yml', mode: '0644' }
        - { src: 'project-compose.yml.j2', dest: 'project-compose.yml', mode: '0644' }

- name: run project-compose up
  ansible.builtin.shell: project-compose up --build -d
  args:
    chdir: "{{ path }}"
  ignore_errors: true
  register: output

- name: debug project-compose output
  ansible.builtin.debug:
    var: output