---
- name: include server install play
  ansible.builtin.import_playbook: server-install.yml

- name: include docker install play
  ansible.builtin.import_playbook: docker-install.yml
  
- name: jenkins docker install
  become: true
  hosts: '{{ hosts }}'
  vars:
    fqdm: 'one-it.uk'
    email: 'admin@{{ fqdm }}'
    jenkins_web_port: '8080'

  roles:
  - roles/jenkins-docker-install

  tasks:

  - name: Allow web port jenkins
    community.general.ufw:
      rule: allow
      route: yes
      src: "{{ nginx_proxy }}"
      port: "{{ item }}"
      proto: tcp
      comment: allow web port jenkins
    loop:
      - "{{ jenkins_web_port }}"
    when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution'] == "Ubuntu"
