---
- name: create dirs
  ansible.builtin.file:
    path: "{{ path }}"
    state: directory
    mode: "0755"
    recurse: true

- name: transfer docker compose files
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ path }}/docker-compose.yml"

- name: deploy docker compose stack
  community.docker.docker_compose:
    docker_src: "{{ path }}"
    files: docker-compose.yml
    state: present
  ignore_errors: true
  register: output

- ansible.builtin.debug:
    var: output
